# Generated by Django 4.1.5 on 2025-02-06 16:49

import apply.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewtime',
            name='time',
            field=models.DateTimeField(validators=[apply.utils.validate_interview_time]),
        ),
    ]
