version: '3.8'

services:
  api:
    build: .
    volumes:
      - static_volunme:/home/app/web/static
    command: gunicorn cspc_web.wsgi:application -w 4 --bind 0.0.0.0:8000
    env_file:
      - ./.env
    expose:
      - 8000
  nginx:
    build: ./nginx
    volumes:
      - static_volunme:/home/app/web/static
    ports:
      - 8004:80
    
    depends_on:
      - api
volumes:
  static_volunme: