version: '3.8'

services:
  api:
    build: ./app
    volumes:
      - static_volunme:/home/app/web/static
      - media_volume:/home/app/web/media
    command: gunicorn cspc_web.wsgi:application -w 4 --bind 0.0.0.0:8000
    env_file:
      - ./app/.env
    expose:
      - 8000
    depends_on:
      - db
  nginx:
    build: ./nginx
    volumes:
      - static_volunme:/home/app/web/static
      - media_volume:/home/app/web/media
    ports:
      - 8004:80
    depends_on:
      - api

  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.db
  dev_api:
    build: 
      context: ./app
      dockerfile: Dockerfile-dev
    command: python manage.py runserver 0.0.0.0:8000 --settings=cspc_web.settings_dev
    volumes:
    - ./app/db:/home/app/web/db
    - dev_media_volume:/home/app/web/media
    ports:
      - "8005:8000"
volumes:
  postgres_data:
  static_volunme:
  media_volume:
  dev_media_volume: