# Generated by Django 4.1.5 on 2024-02-17 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0002_alter_image_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
