# Generated by Django 4.1.5 on 2024-02-20 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0004_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='media')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Apply_Image',
        ),
        migrations.DeleteModel(
            name='Introduce_Image',
        ),
        migrations.DeleteModel(
            name='Login_Image',
        ),
        migrations.DeleteModel(
            name='Main_Image',
        ),
        migrations.DeleteModel(
            name='NotAllow_Image',
        ),
        migrations.DeleteModel(
            name='Result_Image',
        ),
    ]
