# Generated by Django 4.1.5 on 2025-02-06 16:49

from django.db import migrations, models
import image.utils


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0005_image_delete_apply_image_delete_introduce_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to=image.utils.image_rename, validators=[image.utils.validate_file_size]),
        ),
    ]
