FROM python:3.8.13

# 환경 변수 설정
ENV HOME=/home/app
ENV APP_HOME=/home/app/web


# 애플리케이션 디렉터리 생성
RUN mkdir -p $APP_HOME
WORKDIR $APP_HOME

# 파이썬 실행 관련 환경 변수
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# requirements.txt 복사 및 설치
COPY ./requirements.txt $APP_HOME/requirements.txt
RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir --upgrade -r requirements.txt

# .env 파일을 제외하고 모든 파일 복사
COPY . $APP_HOME
RUN rm -f $APP_HOME/.env

RUN sed -i 's/\r$//g' $APP_HOME/entrypoint-dev.sh

RUN chmod +x $APP_HOME/entrypoint-dev.sh 

ENTRYPOINT [ "/home/app/web/entrypoint-dev.sh" ]