# Generated by Django 4.1.5 on 2024-02-14 22:57

from django.db import migrations
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_applicant_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='applicant',
            managers=[
                ('objects', user.models.UserManager()),
            ],
        ),
    ]
