name: Build and Push to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      # Docker Hub 환경 변수 (빌드/푸시 용도)
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./app
          push: true
          tags: |
            ${{ env.DOCKERHUB_USERNAME }}/apply_server:latest
            ${{ env.DOCKERHUB_USERNAME }}/apply_server:${{ github.sha }}
          platforms: linux/amd64,linux/arm64
          cache-from: type=registry,ref=${{ env.DOCKERHUB_USERNAME }}/apply_server:cache
          cache-to: type=inline

      - name: Trigger Release Workflow
        if: success()
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: "release.yml"
          token: ${{ secrets.GITHUB_TOKEN }}
